export const paketData = {
  stream: [
    {
      name: "1",
      speed: "50",
      group: "stream",
      harga: "245.000",
      perangkat: "1 - 4",
      streamtainments: ["catchplay.webp", "firstmediax.webp"],
      cashbackPerMount: "15.000",
      rank: {
        warna: "CD7F32",
        name: "Bronze",
      },
    },
    {
      name: "2",
      speed: "200",
      group: "stream",
      harga: "525.000",
      perangkat: "1 - 8",
      streamtainments: [
        "catchplay.webp",
        "firstmediax.webp",
        "cinemaworld.webp",
      ],
      doubleCashbackPerMount: "50.000",
      extraCashback: "50.000",
      rank: {
        warna: "D7D7D7",
        name: "Silver",
      },
    },
    {
      name: "3",
      speed: "300",
      group: "stream",
      harga: "695.000",
      perangkat: "1 - 15",
      streamtainments: [
        "catchplay.webp",
        "firstmediax.webp",
        "cinemaworld.webp",
        "hbogo.webp",
      ],
      doubleCashbackPerMount: "70.000",
      extraCashback: "50.000",
      rank: {
        warna: "FFD700",
        name: "Gold",
      },
    },
  ],
  joy: [
    {
      name: "1",
      speed: "100",
      group: "joy",
      harga: "295.000",
      perangkat: "1 - 5",
      streamtainments: ["firstmediax.webp"],
      channel: {
        total: "115",
        sd: "69",
        hd: "45",
        fork: "1",
      },
      sudahTermasuk: "First Sport Pack",
      rank: {
        warna: "CD7F32",
        name: "Bronze",
      },
    },
    {
      name: "2",
      speed: "150",
      group: "joy",
      harga: "415.000",
      perangkat: "1 - 8",
      streamtainments: ["firstmediax.webp"],
      channel: {
        total: "115",
        sd: "69",
        hd: "45",
        fork: "1",
      },
      sudahTermasuk: "First Sport Pack",
      doubleCashbackPerMount: "50.000",
      extraCashback: "50.000",
      rank: {
        warna: "D7D7D7",
        name: "Silver",
      },
    },
    {
      name: "3",
      speed: "200",
      group: "joy",
      harga: "665.000",
      perangkat: "9 - 15",
      streamtainments: ["firstmediax.webp"],
      channel: {
        total: "167",
        sd: "89",
        hd: "22",
        fork: "1",
      },
      sudahTermasuk: "Champion TV, Premier Sport, SPOTV",
      doubleCashbackPerMount: "70.000",
      extraCashback: "50.000",
      rank: {
        warna: "FFD700",
        name: "Gold",
      },
    },
  ],
  star: [
    {
      name: "1",
      speed: "300",
      group: "star",
      harga: "975.000",
      perangkat: "1 - 15",
      streamtainments: [
        "catchplay.webp",
        "firstmediax.webp",
        "cinemaworld.webp",
        "hbogo.webp",
      ],
      channel: {
        total: "190",
        sd: "110",
        hd: "89",
        fork: "1",
      },
      doubleCashbackPerMount: "100.000",
      extraCashback: "100.000",
      rank: {
        warna: "CD7F32",
        name: "Bronze",
      },
    },
    {
      name: "2",
      speed: "500",
      group: "star",
      harga: "1.798.500",
      perangkat: "1 - 20",
      streamtainments: [
        "catchplay.webp",
        "firstmediax.webp",
        "cinemaworld.webp",
        "hbogo.webp",
      ],
      channel: {
        total: "196",
        sd: "102",
        hd: "90",
        fork: "4",
      },
      sudahTermasuk: "Smartbox X1",
      doubleCashbackPerMount: "200.000",
      extraCashback: "100.000",
      rank: {
        warna: "D7D7D7",
        name: "Silver",
      },
    },
    {
      name: "3",
      speed: "800",
      group: "star",
      harga: "3.106.500",
      perangkat: "10 - 20",
      streamtainments: [
        "catchplay.webp",
        "firstmediax.webp",
        "cinemaworld.webp",
        "hbogo.webp",
      ],
      channel: {
        total: "213",
        sd: "115",
        hd: "94",
        fork: "4",
      },
      sudahTermasuk: "Smartbox X1",
      doubleCashbackPerMount: "400.000",
      extraCashback: "100.000",
      rank: {
        warna: "FFD700",
        name: "Gold",
      },
    },
  ],
};
